stages:
  
  - test
  - build
  - deploy


run_tests:
  stage: test
  script:
    - npm test

  artifacts:
    paths:
      - coverage/
  only:
    - master


build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build

deploy_app:
  stage: deploy
  script:
    - sshpass -p $PASS ssh -o StrictHostKeyChecking=no projektstudent@10.100.8.137 '
      if [ -d "frontend" ];
        then cd frontend;
        git pull;
      else
        git clone git@git.th-wildau.de:wir/cloudcomputing/ws23-24/frontend.git;
        cd frontend;
      fi;
      npm install;
      npm run build;
      kill $(lsof -t -i:3000);
      serve -s build &> logs.log &
      
      '
  environment:
    name: production
    url: http://10.100.8.137

